import "@/styles/index.css";
import type { Metadata } from "next";
import Main from "@/components/Main";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import WebPlayer from "@/components/web-player";
import AuthContextProvider from "@/context/auth-context";
import { LibraryContextProvider } from "@/context/library-context";
import PlayListContextProvider from "@/context/playlist-context";
import WebPlayerContextProvider from "@/context/web-player-context";
import   'overlayscrollbars/overlayscrollbars.css'
import { Suspense } from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const spotifyFont = localFont({src:'../../assets/fonts/CircularSpotifyTxT-Book.ttf'})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-medium`}>
        <PlayListContextProvider>
          <AuthContextProvider>
            <WebPlayerContextProvider>
              <LibraryContextProvider>
                <div className="flex flex-col absolute inset-0 bg-black">
                  <div className="flex-grow flex w-full h-[90%] sm:p-2 gap-2 overflow-x-hidden">
                    <Navbar />
                    <Main>{children}</Main>
                  </div>
                  <Suspense fallback={<p>jugo</p>}>
                    <WebPlayer />
                  </Suspense>
                </div>
              </LibraryContextProvider>
            </WebPlayerContextProvider>
          </AuthContextProvider>
        </PlayListContextProvider>
      </body>
    </html>
  );
}
