import "@/styles/index.css";
import type { Metadata } from "next";
import Main from "@/components/Main";
import Navbar from "@/components/Navbar";
import Layout from "@/components/Layout";
import localFont from "next/font/local";
import WebPlayer from "@/components/web-player";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const spotifyFont = localFont({src:'../../assets/fonts/CircularSpotifyTxT-Book.ttf'})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={``}>
        <Layout>
          <Navbar />
          <Main>{children}</Main>
        </Layout>
      </body>
    </html>
  );
}
