import "dotenv/config";
import "@/styles/index.css";
import type { Metadata } from "next";
import Main from "@/components/Main";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import WebPlayer from "@/components/web-player";
import AuthContextProvider from "@/context/auth-context";
import { LibraryContextProvider } from "@/context/library-context";
import PlayListContextProvider from "@/context/playlist-context";
import WebPlayerContextProvider from "@/context/web-player-context";
import "overlayscrollbars/overlayscrollbars.css";
import { Suspense } from "react";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import QueryProvider from "@/utils/queryProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const spotifyFont = localFont({src:'../../assets/fonts/CircularSpotifyTxT-Book.ttf'})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={``}>
        <QueryProvider>
          <PlayListContextProvider>
            <AuthContextProvider>
              <WebPlayerContextProvider>
                <LibraryContextProvider>
                  <div className="flex flex-col absolute inset-0 bg-black">
                    <div className="flex w-full basis-[90%] sm:p-2 gap-2 overflow-x-hidden">
                      <Navbar />
                      <Suspense fallback={<h1>Getting things ready</h1>}>
                        <Main>{children}</Main>
                      </Suspense>
                    </div>
                    <Suspense fallback={<p>jugo</p>}>
                      <WebPlayer />
                    </Suspense>
                  </div>
                </LibraryContextProvider>
              </WebPlayerContextProvider>
            </AuthContextProvider>
          </PlayListContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
